'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import styles from './ArchiveLibrary.module.css';
export type ArchiveRecord={path:string;slug:string;title:string;documentId?:string;status:string;documentType?:string;evidenceLevel?:string;reviewStatus?:string;sourceQuality?:string;periodStart?:string;periodEnd?:string;language?:string;batch?:string;topics:string[];geographies:string[];entities:string[];people:string[];dogTypes:string[]};
function haystack(r:ArchiveRecord){return [r.title,r.periodStart,r.periodEnd,...r.topics,...r.geographies,...r.entities,...r.people,...r.dogTypes].filter(Boolean).join(' ').toLowerCase()}
function simpleLevel(v?:string){const x=(v||'').toLowerCase();if(x.includes('confirm'))return'Confirmado';if(x.includes('probab'))return'Probable';if(x.includes('disput'))return'Debatido';if(x.includes('unsupported'))return'No demostrado';if(x.includes('disproven'))return'Refutado';return''}
export function ArchiveLibrary({records}:{records:ArchiveRecord[]}){
 const publicRecords=useMemo(()=>records.filter(r=>r.status!=='methodology'),[records]);const [query,setQuery]=useState('');const [period,setPeriod]=useState('all');
 const periods=[['all','Todas las épocas'],['ancient','Antigüedad'],['medieval','Edad Media'],['modern','Edad Moderna'],['recent','Siglos XIX–XXI']] as const;
 const filtered=useMemo(()=>publicRecords.filter(r=>{if(query&&!haystack(r).includes(query.toLowerCase()))return false;const y=Number(r.periodStart);if(period==='ancient'&&(!Number.isFinite(y)||y>=500))return false;if(period==='medieval'&&(!Number.isFinite(y)||y<500||y>=1500))return false;if(period==='modern'&&(!Number.isFinite(y)||y<1500||y>=1800))return false;if(period==='recent'&&(!Number.isFinite(y)||y<1800))return false;return true}),[publicRecords,query,period]);
 return <main className={styles.page}><section className={styles.hero}><div><span className="eyebrow">Biblioteca</span><h1>Lee las fuentes detrás de la historia.</h1><p>Documentos históricos, estudios, obras, leyes y registros reunidos para entender mejor al Galgo Español. Busca por tema, persona, lugar o época.</p></div></section>
 <section className={`${styles.controls} glass-panel`}><label className={styles.search}><span>¿Qué quieres encontrar?</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Por ejemplo: Salamanca, Roma, arte, abandono…"/></label><div className={styles.facets}><label><span>Época</span><select value={period} onChange={e=>setPeriod(e.target.value)}>{periods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><div className={styles.controlFoot}><span>{filtered.length} lecturas</span>{(query||period!=='all')&&<button onClick={()=>{setQuery('');setPeriod('all')}}>Ver todo</button>}</div></section>
 <section className={styles.library}>{filtered.map((r,i)=><article className={styles.card} key={r.path}><div className={styles.index}>{String(i+1).padStart(2,'0')}</div><div className={styles.cardBody}><div className={styles.chips}>{simpleLevel(r.evidenceLevel)&&<span>{simpleLevel(r.evidenceLevel)}</span>}{r.periodStart&&<span>{r.periodStart}{r.periodEnd?`–${r.periodEnd}`:''}</span>}</div><h2><Link href={`/archive/${r.slug}`}>{r.title}</Link></h2>{!!r.topics.length&&<div className={styles.tags}>{r.topics.slice(0,4).map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div>}<div className={styles.actions}><Link href={`/archive/${r.slug}`}>Leer →</Link><Link href={`/ask?lang=es&q=${encodeURIComponent(r.title)}`}>Preguntar sobre esto →</Link></div></div></article>)}{!filtered.length&&<div className={styles.empty}><strong>No hemos encontrado una lectura con esos términos.</strong><button onClick={()=>{setQuery('');setPeriod('all')}}>Volver a ver todo</button></div>}</section></main>;
}
