'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {institutionalEdges as fallbackEdges,institutionalNodes as fallbackNodes,graphSourceSlug,type InstitutionalEdge,type InstitutionalNode} from '@/lib/institutional-map';
import {emitResearchContext} from '@/lib/research-context';
import {InstitutionalExplorerLive} from '@/components/InstitutionalExplorerLive';
import styles from './MobileInstitutionalExplorer.module.css';

type ApiNode={type:string;label:string;properties?:Record<string,unknown>};type ApiEdge={source:string;predicate:string;target:string;confidence:number;repositoryPath:string};type ApiGraph={nodes:ApiNode[];relationships:ApiEdge[]};
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const layoutByLabel=new Map(fallbackNodes.map(n=>[norm(n.label),n]));
function adapt(api:ApiGraph|null){if(!api)return {nodes:fallbackNodes,edges:fallbackEdges};const nodes=api.nodes.map((n,i)=>{const layout=layoutByLabel.get(norm(n.label));const props=n.properties||{};return {id:layout?.id||norm(n.label)||`n-${i}`,label:n.label,type:String(props.organization_type||n.type||'ENTITY').toUpperCase(),stance:props.stance?String(props.stance):layout?.stance,properties:props,x:layout?.x??50,y:layout?.y??50} satisfies InstitutionalNode});const byLabel=new Map(nodes.map(n=>[norm(n.label),n.id]));const edges=api.relationships.map((e,i)=>({id:`mobile-live-${i}`,source:byLabel.get(norm(e.source))||norm(e.source),target:byLabel.get(norm(e.target))||norm(e.target),predicate:e.predicate,confidence:e.confidence,repositoryPath:e.repositoryPath} satisfies InstitutionalEdge)).filter(e=>nodes.some(n=>n.id===e.source)&&nodes.some(n=>n.id===e.target));return {nodes,edges}}
const copy={en:{kicker:'Mobile institutional explorer',title:'Start with an institution. Follow the documented relationships.',dek:'On a phone, relationships come before spatial layout. The network map remains available as a secondary view.',search:'Search institutions',all:'All institutions',relations:'direct relationships',none:'No direct relationships are stored for this institution.',source:'Canonical source',ask:'Ask Archive',map:'View network map',focus:'Return to institution view',live:'Live graph',fallback:'Fallback snapshot'},es:{kicker:'Explorador institucional móvil',title:'Empieza por una institución. Sigue las relaciones documentadas.',dek:'En móvil, las relaciones van antes que la disposición espacial. El mapa de red sigue disponible como vista secundaria.',search:'Buscar instituciones',all:'Todas las instituciones',relations:'relaciones directas',none:'No hay relaciones directas almacenadas para esta institución.',source:'Fuente canónica',ask:'Preguntar al Archivo',map:'Ver mapa de red',focus:'Volver a instituciones',live:'Grafo en vivo',fallback:'Copia de respaldo'}} as const;

export function MobileInstitutionalExplorer({locale}:{locale:'en'|'es'}){
 const t=copy[locale];const params=useSearchParams();const router=useRouter();const [api,setApi]=useState<ApiGraph|null>(null);const [live,setLive]=useState(false);const [query,setQuery]=useState('');const [mapMode,setMapMode]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch('/api/institutional-graph',{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then((g:ApiGraph)=>{setApi(g);setLive(true)}).catch(()=>setLive(false));return()=>c.abort()},[]);
 const {nodes,edges}=useMemo(()=>adapt(api),[api]);const selectedId=params.get('node');const selected=nodes.find(n=>n.id===selectedId)||null;
 const filtered=useMemo(()=>nodes.filter(n=>!query||n.label.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.label.localeCompare(b.label)),[nodes,query]);
 const direct=selected?edges.filter(e=>e.source===selected.id||e.target===selected.id):[];
 const choose=(node:InstitutionalNode)=>{const next=new URLSearchParams(params.toString());next.delete('edge');next.set('node',node.id);router.replace(`?${next.toString()}`,{scroll:false});emitResearchContext({surface:'graph',kind:'node',label:node.label,href:`/${locale}/graph?node=${node.id}`,detail:`${direct.length} ${t.relations}`})};
 if(mapMode)return <main className={styles.mobile}><button className={styles.mapBack} onClick={()=>setMapMode(false)}>← {t.focus}</button><div className={styles.embeddedMap}><InstitutionalExplorerLive locale={locale}/></div></main>;
 return <main className={styles.mobile}><section className={styles.hero}><span className="eyebrow">{t.kicker}</span><h1>{t.title}</h1><p>{t.dek}</p><div className={styles.status}><span>{nodes.length} {locale==='es'?'nodos':'nodes'}</span><span>{edges.length} {locale==='es'?'relaciones':'relationships'}</span><span>{live?t.live:t.fallback}</span></div></section>
 <div className={styles.search}><label><span>{t.search}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={locale==='es'?'RFEC, SOS Galgos, FCI…':'RFEC, SOS Galgos, FCI…'}/></label><button onClick={()=>setMapMode(true)}>{t.map} →</button></div>
 {!selected?<section className={styles.list}>{filtered.map(node=>{const count=edges.filter(e=>e.source===node.id||e.target===node.id).length;return <button key={node.id} onClick={()=>choose(node)}><div><strong>{node.label}</strong><span>{node.type.replaceAll('_',' ').toLowerCase()}</span></div><b>{count}</b><small>{t.relations}</small></button>})}</section>:<section className={styles.focus}><button className={styles.back} onClick={()=>{const next=new URLSearchParams(params.toString());next.delete('node');router.replace(next.toString()?`?${next.toString()}`:`/${locale}/graph`,{scroll:false})}}>← {t.all}</button><div className={styles.focusHead}><span>{selected.type.replaceAll('_',' ')}</span><h2>{selected.label}</h2>{selected.stance&&<b>{selected.stance.replaceAll('_',' ')}</b>}<p>{direct.length} {t.relations}</p></div><div className={styles.relationships}>{direct.length?direct.map(edge=>{const outbound=edge.source===selected.id;const other=nodes.find(n=>n.id===(outbound?edge.target:edge.source));return <button key={edge.id} onClick={()=>other&&choose(other)}><span>{outbound?'→':'←'} {edge.predicate.replaceAll('_',' ')}</span><strong>{other?.label}</strong><small>{locale==='es'?'Abrir institución':'Open institution'} →</small></button>}):<p>{t.none}</p>}</div><div className={styles.actions}><Link href={`/archive/${graphSourceSlug}`}>{t.source} →</Link><Link href={`/ask?q=${encodeURIComponent(selected.label)}`}>{t.ask} →</Link></div><aside className={styles.method}>{locale==='es'?'Las relaciones son aristas explícitas almacenadas. La proximidad visual, la oposición y la colaboración no implican causalidad, equivalencia moral ni igual calidad de evidencia.':'Relationships are explicit stored edges. Visual proximity, opposition and collaboration never imply causality, moral equivalence or equal evidence quality.'}</aside></section>}
 </main>;
}
