'use client';

import Link from 'next/link';
import {usePathname,useSearchParams} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {RESEARCH_CONTEXT_EVENT,type ResearchContextItem,type ResearchSurface} from '@/lib/research-context';
import styles from './ResearchSession.module.css';

const STORAGE='galgo7:research-trail:v1';
const MAX_ITEMS=12;

function surfaceFromPath(path:string):ResearchSurface{if(path.includes('/timeline'))return 'timeline';if(path.includes('/graph'))return 'graph';if(path.startsWith('/archive'))return 'archive';if(path.startsWith('/ask'))return 'ask';if(path.startsWith('/journey'))return 'journey';if(path.startsWith('/evidence'))return 'evidence';return 'other'}
function routeLabel(path:string,q:string|null){if(path.startsWith('/ask')&&q)return q;if(path.startsWith('/archive/'))return decodeURIComponent(path.split('/').pop()||'Archive record').replaceAll('-',' ');if(path.includes('/timeline'))return 'Timeline';if(path.includes('/graph'))return 'Institutional graph';if(path.startsWith('/archive'))return 'Archive library';if(path.startsWith('/ask'))return 'Ask Archive';if(path.startsWith('/journey'))return 'Journey';if(path.startsWith('/evidence'))return 'Evidence';return 'GALGO/7'}
function addUnique(items:ResearchContextItem[],item:ResearchContextItem){return [item,...items.filter(x=>x.id!==item.id)].slice(0,MAX_ITEMS)}

export function ResearchSession(){
 const pathname=usePathname();const params=useSearchParams();const [items,setItems]=useState<ResearchContextItem[]>([]);const [open,setOpen]=useState(false);const [hydrated,setHydrated]=useState(false);const q=params.get('q');
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw)setItems(JSON.parse(raw))}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(!hydrated)return;const item:ResearchContextItem={id:`route:${pathname}:${q||''}`,surface:surfaceFromPath(pathname),kind:'route',label:routeLabel(pathname,q),href:`${pathname}${q?`?q=${encodeURIComponent(q)}`:''}`,at:Date.now()};setItems(prev=>addUnique(prev,item))},[hydrated,pathname,q]);
 useEffect(()=>{const handler=(event:Event)=>{const item=(event as CustomEvent<ResearchContextItem>).detail;if(!item?.label||!item?.href)return;setItems(prev=>addUnique(prev,item))};window.addEventListener(RESEARCH_CONTEXT_EVENT,handler as EventListener);return()=>window.removeEventListener(RESEARCH_CONTEXT_EVENT,handler as EventListener)},[]);
 useEffect(()=>{const capture=(event:MouseEvent)=>{const button=(event.target as HTMLElement)?.closest('button');if(!button||button.closest(`.${styles.dock}`))return;if(pathname.includes('/timeline')){const label=button.getAttribute('aria-label');if(label&&button.className.includes('timeline-node')){const clean=label.replace(/^.*?:\s*/,'');setItems(prev=>addUnique(prev,{id:`timeline:event:${clean}`,surface:'timeline',kind:'event',label:clean,href:pathname,detail:label,at:Date.now()}))}}else if(pathname.includes('/graph')){const cls=String(button.className||'');if(cls.includes('_node_')&&!button.getAttribute('aria-label')){const label=(button.querySelector('span')?.textContent||button.textContent||'').trim();if(label&&label.length<140)setItems(prev=>addUnique(prev,{id:`graph:institution:${label}`,surface:'graph',kind:'institution',label,href:pathname,at:Date.now()}))}const aria=button.getAttribute('aria-label');if(aria&&cls.includes('edgeHit'))setItems(prev=>addUnique(prev,{id:`graph:relationship:${aria}`,surface:'graph',kind:'relationship',label:aria,href:pathname,at:Date.now()}))}};window.addEventListener('click',capture,true);return()=>window.removeEventListener('click',capture,true)},[pathname]);
 useEffect(()=>{if(hydrated)try{localStorage.setItem(STORAGE,JSON.stringify(items))}catch{}},[items,hydrated]);
 const focus=items[0];const locale=pathname.startsWith('/es/')?'es':'en';const t=locale==='es'?{trail:'Ruta de investigación',continue:'Seguir investigando',ask:'Preguntar',timeline:'Cronología',graph:'Grafo',archive:'Archivo',clear:'Borrar ruta',empty:'La ruta aparecerá al abrir hechos, instituciones, documentos o preguntas.',note:'La ruta conserva contexto de navegación en este navegador. No es evidencia y nunca modifica la clasificación de una fuente.'}:{trail:'Research trail',continue:'Continue investigating',ask:'Ask',timeline:'Timeline',graph:'Graph',archive:'Archive',clear:'Clear trail',empty:'Your trail will appear as you open events, institutions, documents or questions.',note:'The trail preserves navigation context in this browser. It is not evidence and never changes a source classification.'};
 const generic=new Set(['Timeline','Institutional graph','Archive library','Ask Archive','Journey','Evidence','GALGO/7']);const question=focus?.label&&!generic.has(focus.label)?focus.label:'';
 const actions=useMemo(()=>[{label:t.ask,href:`/ask${question?`?q=${encodeURIComponent(question)}`:''}`},{label:t.timeline,href:`/${locale}/timeline`},{label:t.graph,href:`/${locale}/graph`},{label:t.archive,href:'/archive'}],[locale,question,t.ask,t.timeline,t.graph,t.archive]);
 const clear=()=>{setItems([]);try{localStorage.removeItem(STORAGE)}catch{}};if(!hydrated)return null;
 return <div className={`${styles.dock} ${open?styles.open:''}`}><button className={styles.trigger} onClick={()=>setOpen(x=>!x)} aria-expanded={open}><span className={styles.pulse}/><b>{t.trail}</b>{focus&&<span>{focus.label}</span>}<i>{open?'×':items.length}</i></button>{open&&<div className={styles.panel}><div className={styles.head}><div><span className="eyebrow">{t.trail}</span><strong>{focus?.label||t.empty}</strong></div>{!!items.length&&<button onClick={clear}>{t.clear}</button>}</div><p className={styles.note}>{t.note}</p><div className={styles.actions}><span>{t.continue}</span>{actions.map(a=><Link key={a.label} href={a.href}>{a.label} →</Link>)}</div><div className={styles.list}>{items.length?items.map((item,i)=><Link href={item.href} key={item.id} className={styles.item}><span>{String(i+1).padStart(2,'0')}</span><div><b>{item.label}</b><small>{item.surface} · {item.kind}</small>{item.detail&&<em>{item.detail}</em>}</div></Link>):<p>{t.empty}</p>}</div></div>}</div>
}
