import Link from 'next/link';
import styles from './Atlas.module.css';

const records=[
 {id:'V01',period:'c. 1125–1150',title:'San Baudelio hunting frescoes',summary:'Medieval Iberian hunting imagery includes elongated dogs in pursuit scenes. Strong evidence for hunting function and broad sighthound-type representation; not proof of modern breed identity.',supports:'Hunting/coursing function; visual type; elite/secular hunting culture in medieval Iberia.',limits:'No direct pedigree, genetic continuity, formal breed identity or securely contemporary breed label.',dims:['function · strong','type · plausible/strong','population · unsupported','name · unresolved','formal breed · n/a'],source:'https://www.metmuseum.org/art/collection/search?q=San%20Baudelio',ask:'What does the San Baudelio evidence actually support about medieval sighthound-type dogs in Iberia?'},
 {id:'V02',period:'1636–1638',title:'Paul de Vos · Un galgo blanco',summary:'The Prado catalogues this seventeenth-century royal-hunting painting explicitly as a galgo, providing an unusually strong visual + naming anchor for early-modern Spain.',supports:'Named galgo identity in the museum catalogue; royal hunting context; strong visual type evidence.',limits:'No direct pedigree to registered modern Galgo Español populations and no proof of genetic purity.',dims:['function · strong context','type · strong','population · unresolved','name · strong catalogue support','formal breed · pre-standard'],source:'https://www.museodelprado.es/coleccion/obra-de-arte/un-galgo-blanco/65c9e49c-0c3a-48ee-b675-02924baac33d',ask:'What can Un galgo blanco by Paul de Vos tell us about the galgo in seventeenth-century Spain?'},
];
const programmes=[
 ['01','PARES + PARES HTR','State archival records and probabilistic handwritten-text discovery. HTR hits must be image-checked before quotation.','https://pares.cultura.gob.es/pares/es/inicio.html'],
 ['02','BNE Digital','Digitized manuscripts, books, engravings, drawings, maps and historic printed culture.','https://www.bne.es/es/catalogos/biblioteca-digital-hispanica'],
 ['03','Hemeroteca Digital','Contemporary newspapers and magazines for named dogs, competitions, clubs, canódromos and social language.','https://www.bne.es/es/catalogos/hemeroteca-digital'],
 ['04','BOE','Canonical national legal text, amendments and consolidated legislation.','https://www.boe.es/'],
 ['05','RSCE + FCI','Primary institutional sources for modern formal breed classification and standard dates—not automatic proof of deep ancestry.','https://www.fci.be/es/nomenclature/GALGO-ESPANOL-285.html'],
 ['06','Museum object records','Object-level visual provenance, rights status, historical context and what an image can—and cannot—support.','https://www.museodelprado.es/'],
] as const;

export const metadata={title:'Evidence Atlas — GALGO/7',description:'Mobile-first visual and material evidence atlas for the Galgo Español.'};

export default function Atlas(){return <main className={styles.page}><div className={styles.inner}>
 <section className={styles.hero}><span className="eyebrow">Visual + material evidence atlas</span><h1>See the evidence. Don’t overread it.</h1><p>Paintings, frescoes, manuscripts and archival objects can reveal function, naming and cultural role. Visual resemblance alone cannot establish ancestry.</p><div className={styles.heroMeta}><span>object-level provenance</span><span>five continuity dimensions</span><span>mobile-first research surface</span></div><div className={styles.principle}><strong>Evidence rule:</strong> an image supports what it depicts and what its object record establishes. It does not become biological continuity because a dog looks familiar.</div></section>
 <section className={styles.section}><div className={styles.sectionHead}><span className="eyebrow">Anchor objects</span><h2>Two images that deserve careful reading.</h2><p>These are high-value anchors already suitable for the research interface. More objects will be added only when provenance and rights status are clear.</p></div><div className={styles.cards}>{records.map(r=><article className={styles.card} key={r.id}><div className={styles.cardTop}><span className={styles.index}>{r.id}</span><span className={styles.period}>{r.period}</span></div><h3>{r.title}</h3><p>{r.summary}</p><div className={styles.supportGrid}><div className={`${styles.support} ${styles.yes}`}><span>What it supports</span><p>{r.supports}</p></div><div className={`${styles.support} ${styles.no}`}><span>What it does not support</span><p>{r.limits}</p></div></div><div className={styles.dimensions}>{r.dims.map(d=><span key={d}>{d}</span>)}</div><div className={styles.actions}><a href={r.source} target="_blank" rel="noreferrer">Open object/source ↗</a><Link href={`/ask?q=${encodeURIComponent(r.ask)}`}>Ask Archive →</Link></div></article>)}</div></section>
 <section className={styles.section}><div className={styles.sectionHead}><span className="eyebrow">Primary-source programme</span><h2>Where the corpus gets stronger next.</h2><p>The next growth phase is not “more text.” It is more primary evidence, better object-level records and clearer provenance.</p></div><div className={styles.programme}>{programmes.map(([id,title,body,url])=><article className={styles.sourceCard} key={id}><b>{id}</b><div><h3>{title}</h3><p>{body}</p><a href={url} target="_blank" rel="noreferrer">Open repository ↗</a></div></article>)}</div></section>
 <aside className={styles.footerNote}><strong>Corpus governance</strong><p>This Atlas is backed by <Link href="/archive/galgo-visual-material-culture-evidence-atlas">Batch 16</Link> and the <Link href="/archive/galgo-espanol-primary-source-archival-roadmap">Batch 15 archival roadmap</Link>. Corpus additions enter runtime storage through the existing Vercel production ingestion path to the Vercel-connected Neon database; this surface does not write to Neon directly.</p></aside>
 </div></main>}
