import Link from 'next/link';
import styles from './Atlas.module.css';

const records=[
 {id:'V01',period:'first half 12th c.',title:'San Baudelio · Hunting Scene',summary:'A Castilian fresco from San Baudelio de Berlanga shows a mounted hunter with elongated dogs pursuing hares. It is strong object-level evidence for medieval Iberian hunting imagery and broad coursing-type morphology, not proof of a modern breed.',supports:'Hunting/coursing function; visual type; elite/secular hunting culture in medieval Iberia.',limits:'No direct pedigree, genetic continuity, formal breed identity or securely contemporary Galgo Español breed label.',dims:['function · strong','type · plausible/strong','population · unsupported','name · unresolved','formal breed · n/a'],source:'https://www.metmuseum.org/art/collection/search/471826',imageSource:'https://commons.wikimedia.org/wiki/File:Hunting_Scene_MET_cdi57-97-1.jpg',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hunting%20Scene%20MET%20cdi57-97-1.jpg?width=1600',alt:'Twelfth-century San Baudelio hunting fresco showing a mounted hunter and elongated dogs pursuing hares.',credit:'Hunting Scene · San Baudelio de Berlanga · The Met 57.97.1',rights:'CC0 1.0 · Metropolitan Museum of Art Open Access',ask:'What does the San Baudelio evidence actually support about medieval sighthound-type dogs in Iberia?'},
 {id:'V02',period:'1636–1638',title:'Paul de Vos · A White Greyhound',summary:'The Prado object record for Paul de Vos’s painting provides a strong seventeenth-century visual and naming anchor associated with the Spanish royal collection. The historical object can illuminate cultural representation and type without establishing a pedigree to the modern breed.',supports:'Named greyhound/galgo object tradition; royal-collection context; strong visual type evidence.',limits:'No direct pedigree to registered modern Galgo Español populations and no proof of genetic purity or uninterrupted biological continuity.',dims:['function · hunting context','type · strong','population · unresolved','name · strong object record','formal breed · pre-standard'],source:'https://www.museodelprado.es/coleccion/obra-de-arte/un-galgo-blanco/65c9e49c-0c3a-48ee-b675-02924baac33d',imageSource:'https://commons.wikimedia.org/wiki/File:Paul_de_Vos_-_A_white_greyhound.jpg',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Paul%20de%20Vos%20-%20A%20white%20greyhound.jpg?width=1400',alt:'Paul de Vos painting of a white spotted greyhound standing in a landscape, dated 1636 to 1638.',credit:'Paul de Vos · A White Greyhound · Museo del Prado P001876',rights:'Public Domain Mark 1.0 · Wikimedia Commons / Museo del Prado',ask:'What can A White Greyhound by Paul de Vos tell us about the galgo or greyhound in seventeenth-century Spain?'},
];
const romanRecords=[
 {id:'R01',period:'3rd–4th c.',title:'AVRA · Augusta Emerita',summary:'Primary excavation evidence records a dog hunting a hare; the excavator calls it “más bien un galgo”. The inscription AVRA is perhaps the animal’s name.',supports:'Hare-hunting function; modern archaeological sighthound description; probable animal naming.',limits:'AVRA is not a certain name assignment; no modern breed identity, pedigree or population bridge.',href:'/archive/avra-hare-hunt-mosaic-merida',ask:'What does the AVRA mosaic from Mérida actually show?'},
 {id:'R02',period:'late 3rd–early 4th c.',title:'Thalassius · Nimbus + Lateras',summary:'The Corduba excavation report depicts mounted Thalassius with dogs Nimbus and Lateras pursuing a hare. Their names belong to the epigraphic programme.',supports:'Named dogs; hare-hunting function; Roman urban-domestic hunting culture.',limits:'The excavators’ word galgos is modern descriptive terminology; no formal modern breed or population continuity.',href:'/archive/thalassius-nimbus-lateras-hare-hunt-mosaic',ask:'Who are Nimbus and Lateras in the Thalassius mosaic from Corduba?'},
 {id:'R03',period:'301–400 CE',title:'Suárez Somonte · Hare Hunt',summary:'The official Museo Nacional de Arte Romano/CER.es record CE37404 confirms a late-Roman mural ensemble from Mérida with a surviving hare-hunt panel.',supports:'Officially catalogued Roman hare-hunting imagery and archaeological provenance.',limits:'The official record does not identify the dog as a modern Galgo Español or establish biological continuity.',href:'/archive/suarez-somonte-roman-hare-hunt',ask:'What does the official Suárez Somonte museum record prove about hare hunting in Roman Mérida?'},
];
const programmes=[
 ['01','PARES + PARES HTR','State archival records and probabilistic handwritten-text discovery. HTR hits must be image-checked before quotation.','https://pares.cultura.gob.es/pares/es/inicio.html'],
 ['02','BNE Digital','Digitized manuscripts, books, engravings, drawings, maps and historic printed culture.','https://www.bne.es/es/catalogos/biblioteca-digital-hispanica'],
 ['03','Hemeroteca Digital','Contemporary newspapers and magazines for named dogs, competitions, clubs, canódromos and social language.','https://www.bne.es/es/catalogos/hemeroteca-digital'],
 ['04','BOE','Canonical national legal text, amendments and consolidated legislation.','https://www.boe.es/'],
 ['05','RSCE + FCI','Primary institutional sources for modern formal breed classification and standard dates—not automatic proof of deep ancestry.','https://www.fci.be/es/nomenclature/GALGO-ESPANOL-285.html'],
 ['06','Museum object records','Object-level visual provenance, rights status, historical context and what an image can—and cannot—support.','https://www.museodelprado.es/'],
] as const;

export const metadata={title:'Evidence Atlas — GALGO/7',description:'Mobile-first visual and material evidence atlas for the Galgo Español.'};

export default function Atlas(){return <main className={styles.page}><div className={styles.inner}>
 <section className={styles.hero}><span className="eyebrow">Visual + material evidence atlas</span><h1>See the evidence. Don’t overread it.</h1><p>Paintings, frescoes, manuscripts and archival objects can reveal function, naming and cultural role. Visual resemblance alone cannot establish ancestry.</p><div className={styles.heroMeta}><span>object-level provenance</span><span>rights-cleared imagery</span><span>five continuity dimensions</span></div><div className={styles.principle}><strong>Evidence rule:</strong> an image supports what it depicts and what its object record establishes. It does not become biological continuity because a dog looks familiar.</div></section>
 <section className={styles.section}><div className={styles.sectionHead}><span className="eyebrow">Anchor objects</span><h2>Look closely. Read cautiously.</h2><p>These images are presented because the reproduction rights and object provenance are clear. Image rights and historical evidentiary strength are recorded separately.</p></div><div className={styles.cards}>{records.map(r=><article className={styles.card} key={r.id}><figure className={styles.objectFigure}><a href={r.image} target="_blank" rel="noreferrer" aria-label={`Open larger image: ${r.title}`}><img src={r.image} alt={r.alt} loading="lazy"/></a><figcaption><span>{r.credit}</span><a href={r.imageSource} target="_blank" rel="noreferrer">{r.rights} ↗</a></figcaption></figure><div className={styles.cardTop}><span className={styles.index}>{r.id}</span><span className={styles.period}>{r.period}</span></div><h3>{r.title}</h3><p>{r.summary}</p><div className={styles.supportGrid}><div className={`${styles.support} ${styles.yes}`}><span>What it supports</span><p>{r.supports}</p></div><div className={`${styles.support} ${styles.no}`}><span>What it does not support</span><p>{r.limits}</p></div></div><div className={styles.dimensions}>{r.dims.map(d=><span key={d}>{d}</span>)}</div><div className={styles.actions}><a href={r.source} target="_blank" rel="noreferrer">Open museum object ↗</a><Link href={`/ask?q=${encodeURIComponent(r.ask)}`}>Ask Archive →</Link></div></article>)}</div></section>
 <section className={styles.section}><div className={styles.sectionHead}><span className="eyebrow">Roman-Iberian object records</span><h2>Names and hare hunting enter the object record.</h2><p>These records are surfaced without reproducing institutional imagery whose reuse rights have not been cleared. Their evidence comes from official museum metadata and primary excavation publications.</p></div><div className={styles.programme}>{romanRecords.map(r=><article className={styles.sourceCard} key={r.id}><b>{r.id}</b><div><span className={styles.period}>{r.period}</span><h3>{r.title}</h3><p>{r.summary}</p><p><strong>Supports:</strong> {r.supports}</p><p><strong>Limit:</strong> {r.limits}</p><Link href={r.href}>Open object record →</Link> <Link href={`/ask?q=${encodeURIComponent(r.ask)}`}>Ask Archive →</Link></div></article>)}</div></section>
 <section className={styles.section}><div className={styles.sectionHead}><span className="eyebrow">Primary-source programme</span><h2>Where the corpus gets stronger next.</h2><p>The next growth phase is not “more text.” It is more primary evidence, better object-level records and clearer provenance.</p></div><div className={styles.programme}>{programmes.map(([id,title,body,url])=><article className={styles.sourceCard} key={id}><b>{id}</b><div><h3>{title}</h3><p>{body}</p><a href={url} target="_blank" rel="noreferrer">Open repository ↗</a></div></article>)}</div></section>
 <aside className={styles.footerNote}><strong>Corpus governance</strong><p>This Atlas is backed by <Link href="/archive/galgo-visual-material-culture-evidence-atlas">Batch 16</Link> and the <Link href="/archive/galgo-espanol-primary-source-archival-roadmap">Batch 15 archival roadmap</Link>. Corpus additions enter runtime storage through the existing Vercel production ingestion path to the Vercel-connected Neon database; this surface does not write to Neon directly.</p></aside>
 </div></main>}
